version: '3'

services:
  pragma-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    command: [
      "postgres", 
      "-c", "log_statement=all",
      "-c", "max_connections=300",
      "-c", "shared_buffers=80MB"
    ]

  openwhisk:
    container_name: openwhisk
    hostname: openwhisk
    image: openwhisk/standalone:nightly
    restart: always
    ports:
      - 3233:3233
      - 3232:3232
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openwhisk/:/root/.openwhisk