version: '3'

volumes:
  pragma_postgres_data:

services:
  pragma_postgres:
    image: postgres:13.0
    container_name: pragma_daemon_db
    restart: always
    network_mode: bridge
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 9153:5432
    volumes:
      - pragma_postgres_data:/var/lib/postgresql/data
    command: [ "postgres",  "-c", "log_statement=all" ]

  openwhisk:
    container_name: openwhisk
    hostname: openwhisk
    image: openwhisk/standalone:nightly
    restart: always
    ports:
      - 7491:3233
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openwhisk/:/root/.openwhisk

  pragmad:
    image: pragmalang/pragmad:latest
    restart: always
    ports: 
      - 9584:9584
    network_mode: host
    environment:
      DAEMON_HOSTNAME: localhost
      DAEMON_PORT: 9584
      DAEMON_PG_HOST: localhost
      DAEMON_PG_PORT: 9153
      DAEMON_PG_DB_NAME: test
      DAEMON_PG_USER: test
      DAEMON_PG_PASSWORD: test 
      DAEMON_WSK_API_URL: http://localhost:7491
      DAEMON_WSK_AUTH_TOKEN: 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
      DAEMON_WSK_API_VERSION: 1
    depends_on:
      - openwhisk
      - pragma_postgres
